import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { AppSidebar } from "@/components/sidebar/Sidebar-app";
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import Header from "@/components/header/Header";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Agric",
  description: "Generated by carlos",
  icons: {
    icon: "/logo.png",
  }
};






export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        > 
            
          {/* <Header/> */}
          
          <SidebarProvider >
            <AppSidebar />
            <SidebarInset >
              <Header/>
              <div className="flex flex-1 flex-col gap-4 pt-0 bg-[--bg-main] relative ">
                 {children}   
                {/* <div className="grid auto-rows-min gap-4 md:grid-cols-3">
                  <div className="aspect-video rounded-xl bg-muted/50" />
                  <div className="aspect-video rounded-xl bg-muted/50" />
                  <div className="aspect-video rounded-xl bg-muted/50" />
                </div>
                <div className="min-h-[100vh] flex-1 rounded-xl bg-muted/50 md:min-h-min" /> */}
              </div>
            </SidebarInset>
          </SidebarProvider>

          <Footer/>
      </body>
    </html>
  );
}
